version: 2.1
orbs:
  shellcheck: circleci/shellcheck@1
commands:
  rubocop:
    description: Lint Ruby sources with RuboCop
    parameters:
      target:
        type: string
    steps:
      - restore_cache:
          keys:
            - ruby-bundler-v2-extn-{{ checksum "<< parameters.target >>/Gemfile.lock" }}
      - run:
          name: Bundle Install
          working_directory: << parameters.target >>
          command: bundle install --path "$HOME/vendor/$LOCKFILE_CHECKSUM"
          environment:
            LOCKFILE_CHECKSUM: "{{ checksum '<< parameters.target >>/Gemfile.lock' }}"
      - run:
          name: Lint Ruby With RuboCop
          working_directory: << parameters.target >>
          command: |
            bundle exec rubocop --version
            bundle exec rubocop
      - save_cache:
          key: ruby-bundler-v2-extn-{{ checksum "<< parameters.target >>/Gemfile.lock" }}
          paths:
            - ~/vendor/{{ checksum "<< parameters.target >>/Gemfile.lock" }}
jobs:
  rust:
    docker:
      - image: circleci/rust:1.37.0-buster
    steps:
      - checkout
      - restore_cache:
          key: rust-cargo-v3-{{ checksum "Cargo.lock" }}
      - run:
          name: Install Rust Toolchain
          command: |
            rustup toolchain install "$(cat rust-toolchain)"
            rustup component add rustfmt
            rustup component add clippy
            rustc --version --verbose
            cargo --version --verbose
            rustfmt --version
            cargo clippy -- --version
      - run:
          # Debian Buster includes ruby 2.5
          # FIXME: we should really be installing 2.6.3 since that is our stdlib dep.
          name: Install MRI Ruby
          command: |
            sudo apt-get install -y ruby-full
            ruby --version
      - run:
          # https://github.com/mruby/mruby/blob/master/doc/guides/compile.md#prerequisites
          name: Install mruby Build Dependencies
          command: |
            sudo apt-get install -y bison
            bison --version
      - run:
          # needed for cc crate in build.rs
          name: Install mruby-sys Build Dependencies
          command: |
            sudo apt-get install -y clang
            clang --version
      - run:
          name: Install emscripten
          command: |
            . scripts/install-emscripten-toolchain.sh
            emcc --version
      - run:
          name: Format Rust Sources
          command: |
            rustfmt --version
            cargo fmt -- --check --color=auto
      - run:
          name: Lint Rust With Clippy
          command: |
            cargo clippy -- --version
            cargo clippy --all-targets --all-features
      - run:
          name: Wasm Build
          command: |
            rustup target add wasm32-unknown-emscripten
            . scripts/install-emscripten-toolchain.sh
            . scripts/activate-wasm-build-env.sh
            cargo build --target wasm32-unknown-emscripten --release
      - save_cache:
          key: rust-cargo-v3-{{ checksum "Cargo.lock" }}
          paths:
            - "~/.cargo"
            - "./target"
      - persist_to_workspace:
          root: target
          paths:
            - wasm32-unknown-emscripten
  ruby:
    docker:
      - image: circleci/ruby:2.6.3
    steps:
      - checkout
      - run:
          name: Install bundler 2
          command: sudo gem install bundler
      - rubocop:
          target: .
  js:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: js-yarn-v2-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: js-yarn-v2-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - run:
          name: Fake Wasm Sources
          command: |
            mkdir -p target/wasm32-unknown-emscripten/debug
            touch target/wasm32-unknown-emscripten/debug/playground.js
            touch target/wasm32-unknown-emscripten/debug/playground.wasm
            mkdir -p target/wasm32-unknown-emscripten/release
            touch target/wasm32-unknown-emscripten/release/playground.js
            touch target/wasm32-unknown-emscripten/release/playground.wasm
      - run:
          name: yarn check
          command: |
            yarn check --integrity
            yarn check --verify-tree
      - run:
          name: Lint JavaScript with eslint
          command: |
            yarn run eslint --ext .html,.js .
  shell-format:
    docker:
      - image: peterdavehello/shfmt:latest
    steps:
      - checkout
      - run:
          name: Format Shell Sources
          command: |
            shfmt -version
            shfmt -f . | grep -v target/ | grep -v node_modules/ | grep -v vendor/ | xargs shfmt -i 2 -ci -s -w
  text:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: text-yarn-v2-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: text-yarn-v2-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - run:
          name: Format Text Sources
          command: |
            ./scripts/format-text.sh --check "css"
            ./scripts/format-text.sh --check "html"
            ./scripts/format-text.sh --check "js"
            ./scripts/format-text.sh --check "json"
            ./scripts/format-text.sh --check "yaml"
            ./scripts/format-text.sh --check "yml"
            ./scripts/format-text.sh --check "md"
  deploy:
    docker:
      - image: node:lts
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "55:f0:9b:74:3a:ff:3b:33:1e:bc:98:e7:63:6c:ed:bd"
      - attach_workspace:
          at: target
      - run: npm install -g gh-pages@2.1.1
      - run: yarn install
      - run:
          name: Build with Webpack
          command: yarn webpack --mode production
      - run:
          name: Copy doc asset overrides
          command: cp assets/* target/dist
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            gh-pages \
              --user "Artichoke CI <ci@artichokeruby.org>" \
              --message "[skip ci] build docs" \
              --dist target/dist
workflows:
  version: 2
  build:
    jobs:
      - rust
      - ruby
      - js
      - shell-format
      - shellcheck/check:
          exclude: "*/vendor/*"
      - text
      - deploy:
          requires:
            - rust
          filters:
            branches:
              only: master
