---
name: Playground
"on":
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
  schedule:
    - cron: "0 0 * * TUE"
concurrency:
  group: playground-${{ github.head_ref }}
jobs:
  build:
    name: Build Playground
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set toolchain versions
        run: |
          echo "::set-output name=rust::$(cat rust-toolchain)"
          echo "::set-output name=emscripten::$(cat emscripten-toolchain)"
        id: toolchain_versions

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-emscripten
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v1

      - name: Install Ruby toolchain
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ".ruby-version"
          bundler-cache: true

      - name: Cache emsdk
        uses: actions/cache@v3.0.3
        id: cache
        with:
          path: "emsdk-cache"
          key: emscripten-emsdk-${{ runner.os }}-emsdk-${{ steps.toolchain_versions.outputs.emscripten }}

      - name: Install Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{ steps.toolchain_versions.outputs.emscripten }}
          actions-cache-folder: "emsdk-cache"

      - name: Verify emcc version
        run: emcc -v

      - name: Install Nodejs toolchain
        run: npm ci

      - name: Compile Wasm
        run: ruby scripts/build-wasm.rb --release --verbose

      - name: Build Webapp
        run: node build.mjs --release

      - name: Deploy Playground
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/trunk'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          cname: artichoke.run
          user_name: artichoke-ci
          user_email: ci@artichokeruby.org
